apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-fanout
  namespace: merge-openapi
  annotations:
    ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*)
        backend:
          serviceName: merge-openapi-api
          servicePort: 13000
      - path: /result(/|$)(.*)
        backend:
          serviceName: merge-openapi-ui
          servicePort: 13004
      - path: /config(/|$)(.*)
        backend:
          serviceName: merge-openapi-configuration-ui
          servicePort: 13006
